aesni_load="YES"
geom_eli_load="YES"
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
acpi_load="YES"
screen.font="8x16"
splash="/boot/images/FreeBSD-logo-light.png"
boot_mute="YES"
vmm_load="YES"
if_tap_load="YES"
linux64_load="YES"
hw.vmm.ppt_devs="0/20/3"
