aesni_load="YES"
acpi_load="YES"
geom_eli_load="YES"
geom_mirror_load="YES"
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
kern.vty=vt
snd_hda_load="YES"
hw.psm.snaptics_support=1
i915kms_load="YES"
vbe_max_resolution="1080p"
screen.font="8x16"
