#!/usr/bin/env dash

pkill fuzzel 2>/dev/null

entries=" Logout
 Reboot
 Shutdown"

selected=$(printf '%s\n' "$entries" | fuzzel --lines 3 --dmenu --width 13 --anchor top-right --prompt "Session > " | awk '{print tolower($2)}')

case "$selected" in
  logout)
   hyprctl dispatch exit ; killall -u void
    ;;
  reboot)
    doas reboot 
    ;;
   shutdown)
    doas poweroff 
    ;;
esac
