hostname="t490"
keymap="br.kbd"
#wlans_iwm0="wlan0"
#ifconfig_wlan0="WPA  DHCP"
#ifconfig_wlan0_ipv6="inet6 accept_rtadv"
devmatch_enable="YES"
devmatch_blocklist="if_iwlwifi if_iwm"
wifibox_enable="YES"
ifconfig_wifibox0="SYNCDHCP"
background_dhclient_wifibox0="YES"
defaultroute_delay="0"
powerd_enable="YES"
moused_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
dbus_enable="YES"
seatd_enable="YES"
kld_list="i915kms"
linux_enable="YES"
devd_enable="YES"       
allscreens_flags="-f spleen-8x16" 
