# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
hostname="T490BSD"
keymap="br.kbd"
wlans_iwm0="wlan0"
ifconfig_wlan0="WPA  DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
powerd_enable="YES"
moused_enable="YES"
dumpdev="NO"
zfs_enable="YES"
dbus_enable="YES"
seatd_enable="YES"
kld_list="i915kms"
linux_enable="YES"
ifconfig_em0="DHCP"
# weekly_trim_enable="YES"
devd_enable="YES"
powerd_flags="-a hiadaptive -b adaptive"
allscreens_flags="-f spleen-8x16"
