#!/usr/bin/env dash

pkill fuzzel 2>/dev/null
hyprctl dispatch fullscreen 1

entries="  Doc
  Web
  Net
  Main
   Term
  Media
  Desk"

selected=$(printf '%s\n' "$entries" | fuzzel --lines 7 --dmenu --width 13 | awk '{print tolower($2)}')

case "$selected" in
main)
    hyprctl dispatch movetoworkspace 1;;
web)
    hyprctl dispatch movetoworkspace 2;;
net)
    hyprctl dispatch movetoworkspace 3;;
doc)
    hyprctl dispatch movetoworkspace 4;;
term)
    hyprctl dispatch movetoworkspace 5;;
media)
    hyprctl dispatch movetoworkspace 6;;
desk)
    hyprctl dispatch movetoworkspace 7;;
esac
hyprctl dispatch fullscreen 1
