#!/usr/bin/env dash
export NO_AT_BRIDGE=1
dbus-run-session cage -d -s -- \
qemu-system-x86_64 \
-m 8G \
-vga virtio \
-smp 4 \
-audio driver=sdl,model=virtio \
$@

#--bios /home/void/Documents/VMs/OVMF_X64.fd \
