#!/usr/bin/env dash

pkill fuzzel 2>/dev/null

entries="  Off
  On
  wifi-scan"

selected=$(printf '%s\n' "$entries" | fuzzel --lines 3 --dmenu --width 15 --anchor top-right --prompt "Wifi > " | awk '{print tolower($2)}')

case "$selected" in
  off)
   doas service netif stop wifibox0
    ;;
  on)
   doas service netif start wifibox0
    ;;
  wifi-scan)
   foot -e wifiscan
    ;;
esac
